import json
import os

source_file = r"C:\Users\noutp\.gemini\antigravity\scratch\replyvera\locales\en.json"
dest_file = r"C:\Users\noutp\.gemini\antigravity\scratch\replyvera\locales\nl.json"

translations = {
    "Cookie Policy | ReplyVera": "Cookiebeleid | ReplyVera",
    "Reply": "Reply",
    "Vera": "Vera",
    "Product": "Product",
    "Features": "Functies",
    "How It Works": "Hoe Het Werkt",
    "Industries": "Sectoren",
    "Restaurants": "Restaurants",
    "Routine replies with food-safety escalation.": "Standaardreacties met escalatie voor voedselveiligheid.",
    "Dentists & Clinics": "Tandartsen & Klinieken",
    "Privacy-conscious replies for patient reviews.": "Privacybewuste reacties op patiëntbeoordelingen.",
    "Marketing Agencies": "Marketingbureaus",
    "Manage Google review replies for every client.": "Beheer reacties op Google-reviews voor elke klant.",
    "Martial Arts Schools": "Vechtsportscholen",
    "Parent-friendly replies with safety controls.": "Oudervriendelijke reacties met veiligheidscontroles.",
    "Childcare & Preschool": "Kinderopvang & Peuterspeelzalen",
    "Safety-aware responses for parent feedback.": "Veiligheidsbewuste reacties op feedback van ouders.",
    "Tutoring Centers": "Bijlescentra",
    "Professional replies for parent and student reviews.": "Professionele reacties op beoordelingen van ouders en studenten.",
    "Pet Care": "Dierenverzorging",
    "Warm replies with animal-safety escalation.": "Warme reacties met escalatie voor dierenveiligheid.",
    "Car Wash Operators": "Autowasstraten",
    "Track damage, billing, and service complaints.": "Volg klachten over schade, facturering en service.",
    "Laundromats": "Wasserettes",
    "Monitor cleanliness, equipment, and refunds.": "Houd toezicht op netheid, apparatuur en terugbetalingen.",
    "Pricing": "Prijzen",
    "FAQ": "Veelgestelde Vragen",
    "Log In": "Inloggen",
    "Start Free Trial": "Start Gratis Proefperiode",
    "Food-safety escalation and staff recognition": "Escalatie voor voedselveiligheid en erkenning van personeel",
    "Privacy-conscious patient review replies": "Privacybewuste reacties op patiëntbeoordelingen",
    "Manage multiple clients from one dashboard": "Beheer meerdere klanten vanuit één dashboard",
    "Student safety and membership escalation": "Veiligheid van studenten en lidmaatschap escalatie",
    "Child safety and privacy protection": "Veiligheid van kinderen en privacybescherming",
    "Academic claims and refund protection": "Academische claims en bescherming bij terugbetalingen",
    "Warm replies with animal-safety escalation": "Warme reacties met escalatie voor dierenveiligheid",
    "Vehicle damage and billing escalation": "Schade aan voertuigen en escalatie van facturering",
    "Machine, cleanliness, and refund reviews": "Beoordelingen over machines, netheid en terugbetalingen",
    "Cookie Policy": "Cookiebeleid",
    "Last Updated: April 20, 2026": "Laatst bijgewerkt: 20 april 2026",
    "This Cookie Policy explains how ReplyVera uses cookies and similar technologies to recognize you when you visit our website. It explains what these technologies are and why we use them, as well as your rights to control our use of them.": "Dit Cookiebeleid legt uit hoe ReplyVera cookies en vergelijkbare technologieën gebruikt om u te herkennen wanneer u onze website bezoekt. Het legt uit wat deze technologieën zijn, waarom we gebruiken, en wat uw rechten zijn om het gebruik ervan te beheren.",
    "1. What are cookies?": "1. Wat zijn cookies?",
    "Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information.": "Cookies zijn kleine gegevensbestanden die op uw computer of mobiele apparaat worden geplaatst wanneer u een website bezoekt. Cookies worden veelvuldig gebruikt door website-eigenaren om hun websites te laten werken, of om efficiënter te werken, en om rapportage-informatie te verstrekken.",
    "2. Why do we use cookies?": "2. Waarom gebruiken we cookies?",
    "We use first-party and third-party cookies for several reasons. Some cookies are required for technical reasons in order for our Website to operate, and we refer to these as \"essential\" or \"strictly necessary\" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Website.": "We gebruiken first-party en third-party cookies om verschillende redenen. Sommige cookies zijn om technische redenen vereist om onze Website te laten functioneren; deze noemen we \"essentiële\" of \"strikt noodzakelijke\" cookies. Andere cookies stellen ons in staat om de interesses van onze gebruikers te volgen en te targeten om de ervaring op onze Website te verbeteren.",
    "3. Types of cookies we use": "3. Soorten cookies die we gebruiken",
    "These cookies are strictly necessary to provide you with services available through our Website and to use some of its features, such as access to secure areas.": "Deze cookies zijn strikt noodzakelijk om u diensten te kunnen bieden die via onze Website beschikbaar zijn, en om bepaalde functies ervan te kunnen gebruiken, zoals toegang tot beveiligde omgevingen.",
    "Essential Cookies:": "Essentiële cookies:",
    "These cookies collect information that is used either in aggregate form to help us understand how our Website is being used or how effective our marketing campaigns are.": "Deze cookies verzamelen informatie die wordt gebruikt in geaggregeerde vorm om ons te helpen begrijpen hoe onze Website wordt gebruikt of hoe effectief onze marketingcampagnes zijn.",
    "Analytics Cookies:": "Analytische cookies:",
    "These help us remember your login session so you don't have to re-authenticate every time you move between the Dashboard and the site.": "Deze helpen ons uw inlogsessie te onthouden, zodat u niet elke keer opnieuw hoeft in te loggen wanneer u zich tussen het Dashboard en de site beweegt.",
    "Authentication Cookies:": "Authenticatiecookies:",
    "4. How can I control cookies?": "4. Hoe kan ik cookies beheren?",
    "You have the right to decide whether to accept or refuse cookies. You can set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our website though your access to some functionality and areas of our website may be restricted.": "U heeft het recht om te beslissen of u cookies accepteert of weigert. U kunt de instellingen van uw webbrowser aanpassen om cookies te accepteren of te weigeren. Als u ervoor kiest om cookies te weigeren, kunt u onze website nog steeds gebruiken, hoewel uw toegang tot bepaalde functionaliteit en delen van onze website mogelijk beperkt zal zijn.",
    "5. Changes to the Cookie Policy": "5. Wijzigingen in het Cookiebeleid",
    "We may update this Cookie Policy from time to time in order to reflect, for example, changes to the cookies we use or for other operational, legal, or regulatory reasons.": "We kunnen dit Cookiebeleid van tijd tot tijd bijwerken om bijvoorbeeld wijzigingen in de cookies die we gebruiken weer te geven, of om andere operationele, wettelijke of regelgevende redenen.",
    "6. Contact Us": "6. Neem contact met ons op",
    "If you have any questions about our use of cookies or other technologies, please email us at": "Als u vragen heeft over ons gebruik van cookies of andere technologieën, e-mail ons dan op",
    "info@replyvera.com": "info@replyvera.com",
    "Automated Google review responses for small businesses. Plans start at $29 per month.": "Geautomatiseerde reacties op Google-reviews voor kleine bedrijven. Abonnementen beginnen bij $29 per maand.",
    "Currently supporting Google Reviews. Additional platforms are planned.": "Ondersteunt momenteel Google Reviews. Extra platforms staan in de planning.",
    "Company": "Bedrijf",
    "Contact Us": "Neem contact met ons op",
    "Legal": "Juridisch",
    "Terms of Service": "Servicevoorwaarden",
    "Privacy Policy": "Privacybeleid",
    "© 2026 ReplyVera. All rights reserved.": "© 2026 ReplyVera. Alle rechten voorbehouden.",
    "We use cookies to improve your experience and analyze site performance. By clicking \"Accept\", you agree to our use of cookies as outlined in our": "We gebruiken cookies om uw ervaring te verbeteren en de prestaties van de site te analyseren. Door op \"Accepteren\" te klikken, gaat u akkoord met ons gebruik van cookies zoals beschreven in ons",
    "Accept": "Accepteren",
    "Decline": "Weigeren",
    "ReplyVera – Google Review Automation for Small Businesses": "ReplyVera – Google Review Automatisering voor Kleine Bedrijven",
    "Google Review Automation for Small Businesses": "Google Review Automatisering voor Kleine Bedrijven",
    "Meet Vera. Stop Wasting Hours on Google Reviews.": "Maak kennis met Vera. Stop met het verspillen van uren aan Google-reviews.",
    "Vera is your AI assistant that syncs with Google to draft and post custom, brand-compliant replies instantly. Keep customers happy and rank higher—all on autopilot.": "Vera is uw AI-assistent die synchroniseert met Google om direct aangepaste, merkconforme reacties op te stellen en te plaatsen. Houd klanten tevreden en scoor hoger—alles op de automatische piloot.",
    "Available for less than $1 a day": "Beschikbaar voor minder dan $1 per dag",
    "See How It Works": "Bekijk Hoe Het Werkt",
    "Built for Google Reviews \u00a0\u00b7\u00a0 Cancel anytime": "Gemaakt voor Google Reviews \u00a0\u00b7\u00a0 Annuleer op elk moment",
    "replyvera.com/dashboard": "replyvera.com/dashboard",
    "Active": "Actief",
    "Recent Reviews": "Recente Beoordelingen",
    "\"Friendly team and excellent service.\"": "\"Vriendelijk team en uitstekende service.\"",
    "Safe to Auto-Publish": "Veilig om automatisch te publiceren",
    "\"The service took much longer than expected.\"": "\"De service duurde veel langer dan verwacht.\"",
    "Needs Approval": "Goedkeuring vereist",
    "\"This caused an injury.\"": "\"Dit veroorzaakte een blessure.\"",
    "Auto-Publishing Blocked": "Automatisch publiceren geblokkeerd",
    "Review Replies Without the Daily Work": "Reacties op reviews zonder het dagelijkse werk",
    "Save Time": "Bespaar Tijd",
    "Routine Google review responses are drafted or published automatically, freeing your team for more important work.": "Standaardreacties op Google-reviews worden automatisch opgesteld of gepubliceerd, zodat uw team tijd overhoudt voor belangrijker werk.",
    "Sound Personal": "Klinkt Persoonlijk",
    "Every reply reflects the specific review and your preferred business tone. No copy-pasted responses.": "Elke reactie weerspiegelt de specifieke review en uw gewenste bedrijfstoon. Geen gekopieerde en geplakte antwoorden.",
    "Stay in Control": "Houd de Controle",
    "Negative and sensitive reviews are always held for human approval before anything is published.": "Negatieve en gevoelige reviews worden altijd vastgehouden voor menselijke goedkeuring voordat er iets wordt gepubliceerd.",
    "Built-in Safety Controls": "Ingebouwde Veiligheidscontroles",
    "Total Control Over Your Reputation": "Volledige Controle Over Uw Reputatie",
    "Safe replies publish automatically. Sensitive or negative reviews are safely held for your approval.": "Veilige reacties worden automatisch gepubliceerd. Gevoelige of negatieve reviews worden veilig vastgehouden voor uw goedkeuring.",
    "Never worry about an AI saying the wrong thing. Vera automatically analyzes sentiment, flagging anything under 4 stars or containing sensitive keywords for human review.": "Maak u nooit zorgen dat een AI iets verkeerds zegt. Vera analyseert automatisch het sentiment en markeert alles onder de 4 sterren of met gevoelige trefwoorden voor menselijke beoordeling.",
    "Connect Google. Set Your Rules. Let Vera Handle the Rest.": "Koppel Google. Stel Uw Regels In. Laat Vera de Rest Doen.",
    "Introduce Vera to Your Business": "Introduceer Vera in Uw Bedrijf",
    "Securely connect your Google Business Profile in one click so Vera can monitor your incoming reviews.": "Koppel uw Google Bedrijfsprofiel veilig met één klik, zodat Vera uw inkomende reviews kan volgen.",
    "Tell Vera How to Respond": "Vertel Vera Hoe Te Reageren",
    "Set your brand's tone. Tell Vera which reviews she can publish automatically, and which ones you want to review first.": "Stel de toon van uw merk in. Vertel Vera welke reviews ze automatisch kan publiceren, en welke u eerst zelf wilt controleren.",
    "Vera Goes to Work": "Vera Gaat Aan De Slag",
    "Vera instantly drafts and posts personalized responses for routine reviews, saving you hours every single week.": "Vera stelt direct gepersonaliseerde reacties op en plaatst ze voor standaardreviews, wat u wekelijks uren bespaart.",
    "Built for the Way Your Business Handles Reviews": "Gemaakt voor de Manier Waarop Uw Bedrijf Reviews Afhandelt",
    "Choose your industry to see examples, safeguards, and review situations designed for your business.": "Kies uw sector om voorbeelden, veiligheidsmaatregelen en reviewsituaties te zien die zijn ontworpen voor uw bedrijf.",
    "From Routine Praise to Sensitive Complaints": "Van Standaard Complimenten tot Gevoelige Klachten",
    "Vera handles every type of Google review differently, based on what is safe to publish automatically.": "Vera behandelt elk type Google-review anders, gebaseerd op wat veilig is om automatisch te publiceren.",
    "Positive Review": "Positieve Beoordeling",
    "Vera's response": "Reactie van Vera",
    "\"Thank you for the kind words. We're really glad you had a great experience and we appreciate you taking the time to share it.\"": "\"Bedankt voor de vriendelijke woorden. We zijn erg blij dat u een geweldige ervaring had en waarderen het dat u de tijd heeft genomen om dit te delen.\"",
    "Negative Review": "Negatieve Beoordeling",
    "\"Thank you for your feedback. We're sorry your visit took longer than expected and we'll share this with the team.\"": "\"Bedankt voor uw feedback. Het spijt ons dat uw bezoek langer duurde dan verwacht en we zullen dit delen met het team.\"",
    "Sensitive Review": "Gevoelige Beoordeling",
    "Sensitive topic detected": "Gevoelig onderwerp gedetecteerd",
    "A manager must review this before publishing.": "Een manager moet dit beoordelen voor publicatie.",
    "Google Reviews Today. More Platforms Coming Next.": "Vandaag Google Reviews. Binnenkort Meer Platforms.",
    "ReplyVera currently connects directly to Google Business Profile to monitor and respond to Google reviews.": "ReplyVera maakt momenteel direct verbinding met Google Bedrijfsprofiel om Google-reviews te volgen en erop te reageren.",
    "Available Now": "Nu Beschikbaar",
    "Google Reviews": "Google Reviews",
    "Coming Soon": "Binnenkort Beschikbaar",
    "Facebook": "Facebook",
    "Trustpilot": "Trustpilot",
    "Booking.com": "Booking.com",
    "Tripadvisor": "Tripadvisor",
    "What Business Owners Say": "Wat Bedrijfseigenaren Zeggen",
    "See how small businesses use ReplyVera to automate reviews and protect their online reputation.": "Ontdek hoe kleine bedrijven ReplyVera gebruiken om reviews te automatiseren en hun online reputatie te beschermen.",
    "\"As a dentist, patient privacy is everything. ReplyVera’s sensitive topic blocker gives me peace of mind knowing patient reviews are answered professionally without violating HIPAA guidelines.\"": "\"Als tandarts is de privacy van patiënten alles. De blokkering van gevoelige onderwerpen van ReplyVera geeft me de gemoedsrust dat patiëntbeoordelingen professioneel worden beantwoord zonder de AVG-richtlijnen te schenden.\"",
    "Dr. Amit Patel": "Dr. Amit Patel",
    "Patel Dental Group": "Patel Dental Group",
    "\"Our managers spent hours every week replying to reviews. Now, routine 5-star reviews are handled automatically, and we only review wait-time or food feedback. It's a lifesaver.\"": "\"Onze managers spendeerden wekelijks uren aan het beantwoorden van reviews. Nu worden standaard 5-sterrenbeoordelingen automatisch afgehandeld, en beoordelen we alleen wachttijd of feedback over voedsel. Het is een redder in nood.\"",
    "Elena Rostova": "Elena Rostova",
    "The Bistro Group": "The Bistro Group",
    "\"With 3 locations, keeping up with reviews was impossible. Now we manage everything from one dashboard, and the system automatically alerts me if a customer mentions vehicle damage.\"": "\"Met 3 locaties was het bijhouden van reviews onmogelijk. Nu beheren we alles vanuit één dashboard, en het systeem waarschuwt me automatisch als een klant schade aan het voertuig vermeldt.\"",
    "Marcus Vance": "Marcus Vance",
    "Vance Auto Wash": "Vance Auto Wash",
    "Simple Pricing for Small Businesses": "Eenvoudige Prijzen voor Kleine Bedrijven",
    "Start free. No credit card required. Cancel anytime.": "Start gratis. Geen creditcard vereist. Annuleer op elk moment.",
    "Starter": "Starter",
    "$29": "$29",
    "per month": "per maand",
    "You approve every reply before it is published.": "U keurt elke reactie goed voordat deze wordt gepubliceerd.",
    "One location": "Eén locatie",
    "Up to 30 replies per month": "Tot 30 reacties per maand",
    "Manual approval for all reviews": "Handmatige goedkeuring voor alle reviews",
    "Custom tone": "Aangepaste toon",
    "English and Spanish": "Engels en Spaans",
    "Negative-review alerts": "Waarschuwingen voor negatieve reviews",
    "Most Popular": "Meest Populair",
    "Autopilot": "Autopilot",
    "$39": "$39",
    "Safe replies publish automatically. Sensitive reviews stay under your approval.": "Veilige reacties worden automatisch gepubliceerd. Gevoelige reviews blijven onder uw goedkeuring.",
    "Unlimited review responses*": "Onbeperkte reacties op reviews*",
    "Automatic publishing for safe reviews": "Automatisch publiceren voor veilige reviews",
    "Sensitive-review detection": "Detectie van gevoelige reviews",
    "Custom brand voice": "Aangepaste merkstem",
    "Review history": "Geschiedenis van reviews",
    "Multi-Location": "Meerdere Locaties",
    "From $79": "Vanaf $79",
    "Manage all your locations from one account with location-level rules.": "Beheer al uw locaties vanuit één account met regels op locatieniveau.",
    "Three locations included": "Drie locaties inbegrepen",
    "Central dashboard": "Centraal dashboard",
    "Location-specific rules": "Locatiespecifieke regels",
    "Team access": "Toegang voor team",
    "Additional locations available": "Extra locaties beschikbaar",
    "Start Multi-Location Trial": "Start Proefperiode Meerdere Locaties",
    "*Unlimited review responses are subject to reasonable-use limits.": "*Onbeperkte reacties op reviews zijn onderhevig aan grenzen voor redelijk gebruik.",
    "14-day free trial. Cancel anytime.": "14 dagen gratis proefperiode. Annuleer op elk moment.",
    "Frequently Asked Questions": "Veelgestelde Vragen",
    "Which review platforms does ReplyVera support?": "Welke reviewplatforms ondersteunt ReplyVera?",
    "ReplyVera currently supports Google Reviews through Google Business Profile. Facebook, Trustpilot, Booking.com, and Tripadvisor are planned for future releases but are not currently available.": "ReplyVera ondersteunt momenteel Google Reviews via Google Bedrijfsprofiel. Facebook, Trustpilot, Booking.com en Tripadvisor staan op de planning voor toekomstige releases, maar zijn momenteel niet beschikbaar.",
    "Can I approve responses before they are published?": "Kan ik reacties goedkeuren voordat ze worden gepubliceerd?",
    "Yes. On the Starter plan, all replies go through your approval queue before publishing. On Autopilot, you choose which review types can publish automatically and which require your sign-off.": "Ja. In het Starter-abonnement gaan alle reacties via uw goedkeuringswachtrij voordat ze worden gepubliceerd. Met Autopilot kiest u welke typen reviews automatisch kunnen worden gepubliceerd en welke uw goedkeuring vereisen.",
    "Can positive reviews be answered automatically?": "Kunnen positieve reviews automatisch worden beantwoord?",
    "Yes. With the Autopilot plan, routine positive reviews can be published automatically based on your configuration. Negative and sensitive reviews are always held for approval.": "Ja. Met het Autopilot-abonnement kunnen standaard positieve reviews automatisch worden gepubliceerd op basis van uw configuratie. Negatieve en gevoelige reviews worden altijd vastgehouden voor goedkeuring.",
    "Does ReplyVera support multiple locations?": "Ondersteunt ReplyVera meerdere locaties?",
    "Yes. The Multi-Location plan lets you manage multiple Google Business Profile locations from one dashboard, with separate rules and tone settings for each location.": "Ja. Met het Meerdere Locaties-abonnement kunt u meerdere Google Bedrijfsprofiel-locaties beheren vanuit één dashboard, met afzonderlijke regels en tooninstellingen voor elke locatie.",
    "Can I cancel at any time?": "Kan ik op elk moment annuleren?",
    "Yes. There is no long-term contract. You can cancel your subscription at any time from your account settings with no cancellation fees.": "Ja. Er is geen langetermijncontract. U kunt uw abonnement op elk moment annuleren via uw accountinstellingen zonder annuleringskosten.",
    "Start Answering Every Google Review": "Begin met het Beantwoorden van Elke Google Review",
    "Connect your Google Business Profile and let Vera handle routine responses while you stay in control of sensitive feedback.": "Koppel uw Google Bedrijfsprofiel en laat Vera de standaardreacties afhandelen terwijl u de controle houdt over gevoelige feedback.",
    "View Pricing": "Bekijk Prijzen",
    "ReplyVera Pricing – Simple, Transparent Pricing": "ReplyVera Prijzen – Eenvoudige, Transparante Prijzen",
    "Agency": "Bureau",
    "Simple Pricing. No Sales Call Required.": "Eenvoudige Prijzen. Geen Verkoopgesprek Vereist.",
    "Choose the level of automation and number of locations that fit your business.": "Kies het niveau van automatisering en het aantal locaties dat bij uw bedrijf past.",
    "Monthly": "Maandelijks",
    "Annual": "Jaarlijks",
    "Save 2 Months": "Bespaar 2 Maanden",
    "For businesses that approve every reply before publishing.": "Voor bedrijven die elke reactie goedkeuren voor publicatie.",
    "/ month": "/ maand",
    "1 business location": "1 bedrijfslocatie",
    "For businesses that want safe review replies published automatically.": "Voor bedrijven die veilige reacties op reviews automatisch gepubliceerd willen hebben.",
    "For businesses managing several locations.": "Voor bedrijven die meerdere locaties beheren.",
    "From": "Vanaf",
    "For agencies managing Google review replies for multiple clients.": "Voor bureaus die Google review-reacties voor meerdere klanten beheren.",
    "$149": "$149",
    "10 client locations included": "10 klantlocaties inbegrepen",
    "Multi-client dashboard": "Dashboard voor meerdere klanten",
    "Separate client brand voices": "Afzonderlijke merkstemmen voor klanten",
    "Client approval access": "Toegang voor klantgoedkeuring",
    "Agency reporting": "Bureau-rapportage",
    "Start Agency Trial": "Start Proefperiode Bureau",
    "Compare All Features": "Vergelijk Alle Functies",
    "Locations included": "Inbegrepen locaties",
    "3 Locations": "3 Locaties",
    "10 Locations": "10 Locaties",
    "Monthly reply limit": "Maandelijkse reactielimiet",
    "30 replies": "30 reacties",
    "Unlimited": "Onbeperkt",
    "Included": "Inbegrepen",
    "Automatic publishing": "Automatisch publiceren",
    "Not included": "Niet inbegrepen",
    "Employee-name recognition": "Herkenning van medewerkersnamen",
    "Multi-location reporting": "Rapportage over meerdere locaties",
    "Client dashboard": "Klantendashboard",
    "Support level": "Ondersteuningsniveau",
    "Standard": "Standaard",
    "Priority": "Prioriteit",
    "Dedicated": "Toegewijd",
    "Yes. ReplyVera is billed monthly or annually, and you can cancel before your next billing date.": "Ja. ReplyVera wordt maandelijks of jaarlijks gefactureerd, en u kunt annuleren voor uw volgende factureringsdatum.",
    "Is there a setup fee?": "Zijn er instelkosten?",
    "No. There is no setup fee for standard plans.": "Nee. Er zijn geen instelkosten voor standaardabonnementen.",
    "Does each location need its own plan?": "Heeft elke locatie een eigen abonnement nodig?",
    "Starter and Autopilot include one location. Multi-location and Agency plans include several locations and allow additional locations to be added for a fee.": "Starter en Autopilot zijn inclusief één locatie. Multi-Location en Agency abonnementen zijn inclusief meerdere locaties en bieden de mogelijkheid om tegen betaling extra locaties toe te voegen.",
    "Are replies unlimited?": "Zijn reacties onbeperkt?",
    "The Starter plan includes up to 30 replies per month. Autopilot, Multi-Location, and Agency plans include unlimited responses subject to reasonable-use limits.": "Het Starter-abonnement bevat tot 30 reacties per maand. Autopilot, Multi-Location en Agency abonnementen bevatten onbeperkte reacties onder voorbehoud van limieten voor redelijk gebruik.",
    "Which review platforms are supported?": "Welke reviewplatforms worden ondersteund?",
    "ReplyVera currently supports Google Reviews. Facebook, Trustpilot, Booking.com, and Tripadvisor are planned for future releases.": "ReplyVera ondersteunt momenteel Google Reviews. Facebook, Trustpilot, Booking.com en Tripadvisor staan op de planning voor toekomstige releases.",
    "Can I change plans later?": "Kan ik later van abonnement veranderen?",
    "Yes. You can upgrade or downgrade your plan as your review volume or number of locations changes.": "Ja. U kunt uw abonnement upgraden of downgraden naarmate uw reviewvolume of aantal locaties verandert.",
    "Currently supported: Google Reviews": "Momenteel ondersteund: Google Reviews",
    "Facebook, Trustpilot, Booking.com, and Tripadvisor are planned for future releases.": "Facebook, Trustpilot, Booking.com en Tripadvisor staan gepland voor toekomstige releases.",
    "Ready to automate your Google review replies?": "Klaar om uw reacties op Google-reviews te automatiseren?",
    "The review autopilot built for storefronts, franchises, and agencies to protect their online reputation.": "De review-autopilot gebouwd voor winkels, franchises en bureaus om hun online reputatie te beschermen.",
    "Login": "Inloggen",
    "Privacy Policy | ReplyVera": "Privacybeleid | ReplyVera",
    "At ReplyVera, we value your privacy and the trust you place in us to manage your online reputation. This Privacy Policy explains how we collect, use, and protect your information when you use our service.": "Bij ReplyVera hechten we waarde aan uw privacy en het vertrouwen dat u in ons stelt om uw online reputatie te beheren. Dit Privacybeleid legt uit hoe we uw informatie verzamelen, gebruiken en beschermen wanneer u onze service gebruikt.",
    "1. Information We Collect": "1. Informatie die we verzamelen",
    "We collect information to provide a better service to all our users. This includes:": "We verzamelen informatie om een betere service te bieden aan al onze gebruikers. Dit omvat:",
    "When you sign up, we collect your email address and basic profile information via Google OAuth.": "Wanneer u zich aanmeldt, verzamelen we uw e-mailadres en basale profielinformatie via Google OAuth.",
    "Account Information:": "Accountinformatie:",
    "To operate our core service, we request access to your Google Business Profile. This includes review content, reviewer names, and location data.": "Om onze kernservice uit te voeren, vragen we toegang tot uw Google Bedrijfsprofiel. Dit omvat de inhoud van reviews, namen van reviewers en locatiegegevens.",
    "Google Business Profile Data:": "Google Bedrijfsprofielgegevens:",
    "We may collect information about how you interact with our dashboard to improve our user interface and AI performance.": "We kunnen informatie verzamelen over hoe u met ons dashboard communiceert om onze gebruikersinterface en AI-prestaties te verbeteren.",
    "Usage Data:": "Gebruiksgegevens:",
    "2. How We Use Information": "2. Hoe we informatie gebruiken",
    "We use the data we collect for the following purposes:": "We gebruiken de gegevens die we verzamelen voor de volgende doeleinden:",
    "To draft and post replies to your Google reviews using AI.": "Om reacties op uw Google-reviews op te stellen en te plaatsen met behulp van AI.",
    "To provide analytics on your review performance.": "Om analyses van uw reviewprestaties te bieden.",
    "To communicate with you about your account and service updates.": "Om met u te communiceren over uw account en service-updates.",
    "To improve our AI algorithms for more accurate and helpful responses.": "Om onze AI-algoritmen te verbeteren voor nauwkeuriger en nuttiger reacties.",
    "3. Limited Use for Google User Data": "3. Beperkt gebruik van Google-gebruikersgegevens",
    "ReplyVera's use and transfer to any other app of information received from Google APIs will adhere to the": "Het gebruik en de overdracht van ReplyVera naar enige andere app van informatie die is ontvangen van Google API's zal voldoen aan het",
    ", including the Limited Use requirements.": ", inclusief de vereisten voor Beperkt Gebruik.",
    "Google API Services User Data Policy": "Beleid voor Gebruikersgegevens van Google API-services",
    "We do not use your Google data for serving advertisements, and we do not sell your data to third parties.": "We gebruiken uw Google-gegevens niet voor het weergeven van advertenties en we verkopen uw gegevens niet aan derden.",
    "4. Data Retention": "4. Dataretentie",
    "We retain your information as long as your account is active. If you disconnect your Google Account or delete your ReplyVera account, we will remove your tokens and cease data collection immediately.": "We bewaren uw informatie zolang uw account actief is. Als u uw Google-account loskoppelt of uw ReplyVera-account verwijdert, verwijderen we uw tokens en stoppen we onmiddellijk met het verzamelen van gegevens.",
    "5. Security": "5. Veiligheid",
    "We implement industry-standard security measures, including encryption at rest and in transit, to protect your data from unauthorized access or disclosure.": "We implementeren industriestandaard beveiligingsmaatregelen, inclusief encryptie in rust en tijdens verzending, om uw gegevens te beschermen tegen ongeautoriseerde toegang of openbaarmaking.",
    "If you have any questions about this Privacy Policy, please contact us at": "Als u vragen heeft over dit Privacybeleid, neem dan contact met ons op via",
    "Terms of Service | ReplyVera": "Servicevoorwaarden | ReplyVera",
    "By using the ReplyVera service (\"Service\"), you agree to the following terms and conditions. If you do not agree, please do not use the Service.": "Door de ReplyVera-service (\"Service\") te gebruiken, gaat u akkoord met de volgende voorwaarden. Als u niet akkoord gaat, gebruik de Service dan niet.",
    "1. The Service": "1. De Service",
    "ReplyVera provides an AI-assisted review management platform designed to help businesses draft and manage replies to Google Business Profile reviews. The Service includes automated drafting and, where enabled, automated posting of replies.": "ReplyVera biedt een AI-ondersteund platform voor reviewbeheer, ontworpen om bedrijven te helpen bij het opstellen en beheren van reacties op Google Bedrijfsprofiel-reviews. De Service omvat het automatisch opstellen en, indien ingeschakeld, automatisch plaatsen van reacties.",
    "2. User Responsibilities": "2. Verantwoordelijkheden van de Gebruiker",
    "You are responsible for the content posted to your Google Business Profile. While ReplyVera uses advanced AI to draft responses, you acknowledge that:": "U bent verantwoordelijk voor de inhoud die op uw Google Bedrijfsprofiel wordt geplaatst. Hoewel ReplyVera geavanceerde AI gebruikt om reacties op te stellen, erkent u dat:",
    "Automated replies are generated based on AI models and may not always be perfect.": "Automatische reacties worden gegenereerd op basis van AI-modellen en zijn mogelijk niet altijd perfect.",
    "You have the option to review all drafts before they go live.": "U heeft de mogelijkheid om alle concepten te bekijken voordat ze live gaan.",
    "You must comply with Google's Business Profile policies at all times.": "U moet te allen tijde voldoen aan het beleid van Google Bedrijfsprofiel.",
    "3. Access and Permissions": "3. Toegang en Rechten",
    "By connecting your Google Account, you grant ReplyVera permission to access your Google Business Profile, read reviews, and post replies on your behalf. You can revoke this access at any time via your Google Account settings or our Dashboard.": "Door uw Google-account te koppelen, verleent u ReplyVera toestemming om toegang te krijgen tot uw Google Bedrijfsprofiel, reviews te lezen en namens u reacties te plaatsen. U kunt deze toegang op elk moment intrekken via de instellingen van uw Google-account of ons Dashboard.",
    "4. Subscription and Payments": "4. Abonnement en Betalingen",
    "ReplyVera is a subscription-based service. You agree to pay all fees associated with your chosen plan. All payments are processed via our secure third-party provider (Stripe). You may cancel your subscription at any time.": "ReplyVera is een abonnementsservice. U stemt ermee in om alle kosten te betalen die verband houden met uw gekozen abonnement. Alle betalingen worden verwerkt via onze beveiligde externe provider (Stripe). U kunt uw abonnement op elk moment annuleren.",
    "5. Limitation of Liability": "5. Beperking van Aansprakelijkheid",
    "ReplyVera is provided \"as is.\" We are not liable for any damages, loss of reputation, or Google account suspensions resulting from the use of the Service or the content of the AI-generated replies.": "ReplyVera wordt geleverd \"zoals het is\". Wij zijn niet aansprakelijk voor enige schade, reputatieverlies of schorsingen van Google-accounts als gevolg van het gebruik van de Service of de inhoud van de door AI gegenereerde reacties.",
    "6. Termination": "6. Beëindiging",
    "We reserve the right to suspend or terminate accounts that violate these terms, use the service for spam, or engage in deceptive practices regarding customer reviews.": "We behouden ons het recht voor om accounts op te schorten of te beëindigen die deze voorwaarden schenden, de service gebruiken voor spam of zich inlaten met misleidende praktijken met betrekking tot klantbeoordelingen.",
    "7. Changes to Terms": "7. Wijzigingen in Voorwaarden",
    "We may update these Terms from time to time. Your continued use of the Service after changes are posted constitutes acceptance of the new Terms.": "We kunnen deze Voorwaarden van tijd tot tijd bijwerken. Uw voortgezette gebruik van de Service na publicatie van wijzigingen vormt de acceptatie van de nieuwe Voorwaarden.",
    "8. Contact Us": "8. Neem contact met ons op",
    "If you have any questions about these Terms, please contact us at": "Als u vragen heeft over deze Voorwaarden, neem dan contact met ons op via",
}

with open(source_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

for k, v in data.items():
    if v in translations:
        data[k] = translations[v]
    # Otherwise leave the original value intact (e.g. CSS, Javascript snippets)

with open(dest_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Successfully generated {dest_file}")
