import json
import os

source_file = r"C:\Users\noutp\.gemini\antigravity\scratch\replyvera\locales\en.json"
dest_file = r"C:\Users\noutp\.gemini\antigravity\scratch\replyvera\locales\es.json"

translations = {
    "Cookie Policy | ReplyVera": "Política de Cookies | ReplyVera",
    "Reply": "Responder",
    "Vera": "Vera",
    "Product": "Producto",
    "Features": "Características",
    "How It Works": "Cómo Funciona",
    "Industries": "Industrias",
    "Restaurants": "Restaurantes",
    "Routine replies with food-safety escalation.": "Respuestas rutinarias con escalado de seguridad alimentaria.",
    "Dentists & Clinics": "Dentistas y Clínicas",
    "Privacy-conscious replies for patient reviews.": "Respuestas conscientes de la privacidad para reseñas de pacientes.",
    "Marketing Agencies": "Agencias de Marketing",
    "Manage Google review replies for every client.": "Gestiona respuestas a reseñas de Google para cada cliente.",
    "Martial Arts Schools": "Escuelas de Artes Marciales",
    "Parent-friendly replies with safety controls.": "Respuestas amigables para padres con controles de seguridad.",
    "Childcare & Preschool": "Guardería y Preescolar",
    "Safety-aware responses for parent feedback.": "Respuestas conscientes de la seguridad para comentarios de padres.",
    "Tutoring Centers": "Centros de Tutoría",
    "Professional replies for parent and student reviews.": "Respuestas profesionales para reseñas de padres y estudiantes.",
    "Pet Care": "Cuidado de Mascotas",
    "Warm replies with animal-safety escalation.": "Respuestas cálidas con escalado de seguridad animal.",
    "Car Wash Operators": "Operadores de Lavado de Autos",
    "Track damage, billing, and service complaints.": "Rastrea quejas de daños, facturación y servicio.",
    "Laundromats": "Lavanderías",
    "Monitor cleanliness, equipment, and refunds.": "Monitorea limpieza, equipos y reembolsos.",
    "Pricing": "Precios",
    "FAQ": "Preguntas Frecuentes",
    "Log In": "Iniciar Sesión",
    "Start Free Trial": "Comenzar Prueba Gratuita",
    "Food-safety escalation and staff recognition": "Escalado de seguridad alimentaria y reconocimiento del personal",
    "Privacy-conscious patient review replies": "Respuestas a reseñas de pacientes conscientes de la privacidad",
    "Manage multiple clients from one dashboard": "Gestiona múltiples clientes desde un solo panel",
    "Student safety and membership escalation": "Seguridad de estudiantes y escalado de membresía",
    "Child safety and privacy protection": "Seguridad infantil y protección de la privacidad",
    "Academic claims and refund protection": "Reclamos académicos y protección de reembolsos",
    "Warm replies with animal-safety escalation": "Respuestas cálidas con escalado de seguridad animal",
    "Vehicle damage and billing escalation": "Escalado de daños a vehículos y facturación",
    "Machine, cleanliness, and refund reviews": "Reseñas de máquinas, limpieza y reembolsos",
    "Cookie Policy": "Política de Cookies",
    "Last Updated: April 20, 2026": "Última Actualización: 20 de Abril, 2026",
    "This Cookie Policy explains how ReplyVera uses cookies and similar technologies to recognize you when you visit our website. It explains what these technologies are and why we use them, as well as your rights to control our use of them.": "Esta Política de Cookies explica cómo ReplyVera utiliza cookies y tecnologías similares para reconocerle cuando visita nuestro sitio web. Explica qué son estas tecnologías y por qué las usamos, así como sus derechos para controlar nuestro uso de ellas.",
    "1. What are cookies?": "1. ¿Qué son las cookies?",
    "Cookies are small data files that are placed on your computer or mobile device when you visit a website. Cookies are widely used by website owners in order to make their websites work, or to work more efficiently, as well as to provide reporting information.": "Las cookies son pequeños archivos de datos que se colocan en su computadora o dispositivo móvil cuando visita un sitio web. Las cookies son ampliamente utilizadas por los propietarios de sitios web para hacer que sus sitios web funcionen, o funcionen de manera más eficiente, así como para proporcionar información de informes.",
    "2. Why do we use cookies?": "2. ¿Por qué usamos cookies?",
    "We use first-party and third-party cookies for several reasons. Some cookies are required for technical reasons in order for our Website to operate, and we refer to these as \"essential\" or \"strictly necessary\" cookies. Other cookies also enable us to track and target the interests of our users to enhance the experience on our Website.": "Usamos cookies de origen y de terceros por varias razones. Algunas cookies son necesarias por razones técnicas para que nuestro Sitio Web funcione, y nos referimos a estas como cookies \"esenciales\" o \"estrictamente necesarias\". Otras cookies también nos permiten rastrear y orientar los intereses de nuestros usuarios para mejorar la experiencia en nuestro Sitio Web.",
    "3. Types of cookies we use": "3. Tipos de cookies que usamos",
    "These cookies are strictly necessary to provide you with services available through our Website and to use some of its features, such as access to secure areas.": "Estas cookies son estrictamente necesarias para brindarle los servicios disponibles a través de nuestro Sitio Web y para usar algunas de sus funciones, como el acceso a áreas seguras.",
    "Essential Cookies:": "Cookies Esenciales:",
    "These cookies collect information that is used either in aggregate form to help us understand how our Website is being used or how effective our marketing campaigns are.": "Estas cookies recopilan información que se utiliza en forma agregada para ayudarnos a comprender cómo se está utilizando nuestro Sitio Web o qué tan efectivas son nuestras campañas de marketing.",
    "Analytics Cookies:": "Cookies de Análisis:",
    "These help us remember your login session so you don't have to re-authenticate every time you move between the Dashboard and the site.": "Estas nos ayudan a recordar su sesión de inicio de sesión para que no tenga que volver a autenticarse cada vez que se mueva entre el Panel de Control y el sitio.",
    "Authentication Cookies:": "Cookies de Autenticación:",
    "4. How can I control cookies?": "4. ¿Cómo puedo controlar las cookies?",
    "You have the right to decide whether to accept or refuse cookies. You can set or amend your web browser controls to accept or refuse cookies. If you choose to reject cookies, you may still use our website though your access to some functionality and areas of our website may be restricted.": "Usted tiene el derecho de decidir si acepta o rechaza las cookies. Puede configurar o modificar los controles de su navegador web para aceptar o rechazar cookies. Si elige rechazar las cookies, aún puede usar nuestro sitio web, aunque su acceso a algunas funciones y áreas de nuestro sitio web puede estar restringido.",
    "5. Changes to the Cookie Policy": "5. Cambios en la Política de Cookies",
    "We may update this Cookie Policy from time to time in order to reflect, for example, changes to the cookies we use or for other operational, legal, or regulatory reasons.": "Podemos actualizar esta Política de Cookies de vez en cuando para reflejar, por ejemplo, cambios en las cookies que utilizamos o por otras razones operativas, legales o reglamentarias.",
    "6. Contact Us": "6. Contáctenos",
    "If you have any questions about our use of cookies or other technologies, please email us at": "Si tiene alguna pregunta sobre nuestro uso de cookies u otras tecnologías, envíenos un correo electrónico a",
    "info@replyvera.com": "info@replyvera.com",
    "Automated Google review responses for small businesses. Plans start at $29 per month.": "Respuestas automatizadas de reseñas de Google para pequeñas empresas. Los planes comienzan en $29 por mes.",
    "Currently supporting Google Reviews. Additional platforms are planned.": "Actualmente compatible con Reseñas de Google. Se planean plataformas adicionales.",
    "Company": "Empresa",
    "Legal": "Legal",
    "Terms of Service": "Términos de Servicio",
    "Privacy Policy": "Política de Privacidad",
    "© 2026 ReplyVera. All rights reserved.": "© 2026 ReplyVera. Todos los derechos reservados.",
    "We use cookies to improve your experience and analyze site performance. By clicking \"Accept\", you agree to our use of cookies as outlined in our": "Usamos cookies para mejorar su experiencia y analizar el rendimiento del sitio. Al hacer clic en \"Aceptar\", acepta nuestro uso de cookies como se describe en nuestra",
    "Accept": "Aceptar",
    "Decline": "Rechazar",
    "ReplyVera – Google Review Automation for Small Businesses": "ReplyVera – Automatización de Reseñas de Google para Pequeñas Empresas",
    "Google Review Automation for Small Businesses": "Automatización de Reseñas de Google para Pequeñas Empresas",
    "Meet Vera. Stop Wasting Hours on Google Reviews.": "Conoce a Vera. Deja de perder horas en Reseñas de Google.",
    "Vera is your AI assistant that syncs with Google to draft and post custom, brand-compliant replies instantly. Keep customers happy and rank higher—all on autopilot.": "Vera es tu asistente de IA que se sincroniza con Google para redactar y publicar respuestas personalizadas y acordes a la marca al instante. Mantén a los clientes felices y sube de rango, todo en piloto automático.",
    "Available for less than $1 a day": "Disponible por menos de $1 al día",
    "See How It Works": "Ver Cómo Funciona",
    "Built for Google Reviews \u00a0\u00b7\u00a0 Cancel anytime": "Creado para Reseñas de Google \u00a0\u00b7\u00a0 Cancela en cualquier momento",
    "replyvera.com/dashboard": "replyvera.com/dashboard",
    "Active": "Activo",
    "Recent Reviews": "Reseñas Recientes",
    "\"Friendly team and excellent service.\"": "\"Equipo amable y excelente servicio.\"",
    "Safe to Auto-Publish": "Seguro para Publicación Automática",
    "\"The service took much longer than expected.\"": "\"El servicio tardó mucho más de lo esperado.\"",
    "Needs Approval": "Necesita Aprobación",
    "\"This caused an injury.\"": "\"Esto causó una lesión.\"",
    "Auto-Publishing Blocked": "Publicación Automática Bloqueada",
    "Review Replies Without the Daily Work": "Respuestas a Reseñas Sin el Trabajo Diario",
    "Save Time": "Ahorra Tiempo",
    "Routine Google review responses are drafted or published automatically, freeing your team for more important work.": "Las respuestas rutinarias a reseñas de Google se redactan o publican automáticamente, liberando a tu equipo para trabajos más importantes.",
    "Sound Personal": "Suena Personal",
    "Every reply reflects the specific review and your preferred business tone. No copy-pasted responses.": "Cada respuesta refleja la reseña específica y el tono preferido de tu empresa. Sin respuestas copiadas y pegadas.",
    "Stay in Control": "Mantén el Control",
    "Negative and sensitive reviews are always held for human approval before anything is published.": "Las reseñas negativas y confidenciales siempre se retienen para aprobación humana antes de que se publique nada.",
    "Built-in Safety Controls": "Controles de Seguridad Incorporados",
    "Total Control Over Your Reputation": "Control Total Sobre tu Reputación",
    "Safe replies publish automatically. Sensitive or negative reviews are safely held for your approval.": "Las respuestas seguras se publican automáticamente. Las reseñas delicadas o negativas se retienen de forma segura para tu aprobación.",
    "Never worry about an AI saying the wrong thing. Vera automatically analyzes sentiment, flagging anything under 4 stars or containing sensitive keywords for human review.": "Nunca te preocupes por que una IA diga algo incorrecto. Vera analiza automáticamente el sentimiento, marcando cualquier cosa por debajo de 4 estrellas o que contenga palabras clave confidenciales para revisión humana.",
    "Connect Google. Set Your Rules. Let Vera Handle the Rest.": "Conecta Google. Establece Tus Reglas. Deja que Vera Haga el Resto.",
    "Introduce Vera to Your Business": "Presenta a Vera a Tu Empresa",
    "Securely connect your Google Business Profile in one click so Vera can monitor your incoming reviews.": "Conecta de forma segura tu Perfil de Empresa de Google con un clic para que Vera pueda monitorear tus reseñas entrantes.",
    "Tell Vera How to Respond": "Dile a Vera Cómo Responder",
    "Set your brand's tone. Tell Vera which reviews she can publish automatically, and which ones you want to review first.": "Establece el tono de tu marca. Dile a Vera qué reseñas puede publicar automáticamente y cuáles quieres revisar primero.",
    "Vera Goes to Work": "Vera se Pone a Trabajar",
    "Vera instantly drafts and posts personalized responses for routine reviews, saving you hours every single week.": "Vera redacta y publica al instante respuestas personalizadas para reseñas rutinarias, ahorrándote horas cada semana.",
    "Built for the Way Your Business Handles Reviews": "Creado para la Forma en que tu Empresa Maneja las Reseñas",
    "Choose your industry to see examples, safeguards, and review situations designed for your business.": "Elige tu industria para ver ejemplos, medidas de seguridad y situaciones de reseñas diseñadas para tu negocio.",
    "From Routine Praise to Sensitive Complaints": "Desde Elogios Rutinarios hasta Quejas Delicadas",
    "Vera handles every type of Google review differently, based on what is safe to publish automatically.": "Vera maneja cada tipo de reseña de Google de manera diferente, según lo que sea seguro publicar automáticamente.",
    "Positive Review": "Reseña Positiva",
    "Vera's response": "Respuesta de Vera",
    "\"Thank you for the kind words. We're really glad you had a great experience and we appreciate you taking the time to share it.\"": "\"Gracias por las amables palabras. Nos alegra mucho que hayas tenido una gran experiencia y agradecemos que te tomes el tiempo de compartirlo.\"",
    "Negative Review": "Reseña Negativa",
    "\"Thank you for your feedback. We're sorry your visit took longer than expected and we'll share this with the team.\"": "\"Gracias por tu opinión. Lamentamos que tu visita haya tardado más de lo esperado y compartiremos esto con el equipo.\"",
    "Sensitive Review": "Reseña Delicada",
    "Sensitive topic detected": "Tema delicado detectado",
    "A manager must review this before publishing.": "Un gerente debe revisar esto antes de publicarlo.",
    "Google Reviews Today. More Platforms Coming Next.": "Reseñas de Google Hoy. Más Plataformas Próximamente.",
    "ReplyVera currently connects directly to Google Business Profile to monitor and respond to Google reviews.": "ReplyVera se conecta actualmente directamente al Perfil de Empresa de Google para monitorear y responder a las reseñas de Google.",
    "Available Now": "Disponible Ahora",
    "Google Reviews": "Reseñas de Google",
    "Coming Soon": "Próximamente",
    "Facebook": "Facebook",
    "Trustpilot": "Trustpilot",
    "Booking.com": "Booking.com",
    "Tripadvisor": "Tripadvisor",
    "What Business Owners Say": "Lo Que Dicen los Dueños de Negocios",
    "See how small businesses use ReplyVera to automate reviews and protect their online reputation.": "Mira cómo las pequeñas empresas utilizan ReplyVera para automatizar reseñas y proteger su reputación en línea.",
    "\"As a dentist, patient privacy is everything. ReplyVera’s sensitive topic blocker gives me peace of mind knowing patient reviews are answered professionally without violating HIPAA guidelines.\"": "\"Como dentista, la privacidad del paciente lo es todo. El bloqueador de temas delicados de ReplyVera me da tranquilidad al saber que las reseñas de los pacientes se responden profesionalmente sin violar las pautas de HIPAA.\"",
    "Dr. Amit Patel": "Dr. Amit Patel",
    "Patel Dental Group": "Patel Dental Group",
    "\"Our managers spent hours every week replying to reviews. Now, routine 5-star reviews are handled automatically, and we only review wait-time or food feedback. It's a lifesaver.\"": "\"Nuestros gerentes pasaban horas cada semana respondiendo a las reseñas. Ahora, las reseñas de 5 estrellas de rutina se manejan automáticamente, y solo revisamos los comentarios sobre el tiempo de espera o la comida. Es un salvavidas.\"",
    "Elena Rostova": "Elena Rostova",
    "The Bistro Group": "The Bistro Group",
    "\"With 3 locations, keeping up with reviews was impossible. Now we manage everything from one dashboard, and the system automatically alerts me if a customer mentions vehicle damage.\"": "\"Con 3 ubicaciones, mantenerse al día con las reseñas era imposible. Ahora gestionamos todo desde un solo panel, y el sistema me alerta automáticamente si un cliente menciona daños en el vehículo.\"",
    "Marcus Vance": "Marcus Vance",
    "Vance Auto Wash": "Vance Auto Wash",
    "Simple Pricing for Small Businesses": "Precios Sencillos para Pequeñas Empresas",
    "Start free. No credit card required. Cancel anytime.": "Comienza gratis. No se requiere tarjeta de crédito. Cancela en cualquier momento.",
    "Starter": "Starter",
    "$29": "$29",
    "per month": "por mes",
    "You approve every reply before it is published.": "Tú apruebas cada respuesta antes de que se publique.",
    "One location": "Una ubicación",
    "Up to 30 replies per month": "Hasta 30 respuestas por mes",
    "Manual approval for all reviews": "Aprobación manual para todas las reseñas",
    "Custom tone": "Tono personalizado",
    "English and Spanish": "Inglés y Español",
    "Negative-review alerts": "Alertas de reseñas negativas",
    "Most Popular": "Más Popular",
    "Autopilot": "Piloto Automático",
    "$39": "$39",
    "Safe replies publish automatically. Sensitive reviews stay under your approval.": "Las respuestas seguras se publican automáticamente. Las reseñas delicadas permanecen bajo tu aprobación.",
    "Unlimited review responses*": "Respuestas ilimitadas a reseñas*",
    "Automatic publishing for safe reviews": "Publicación automática para reseñas seguras",
    "Sensitive-review detection": "Detección de reseñas delicadas",
    "Custom brand voice": "Voz de marca personalizada",
    "Review history": "Historial de reseñas",
    "Multi-Location": "Multi-Ubicación",
    "From $79": "Desde $79",
    "Manage all your locations from one account with location-level rules.": "Gestiona todas tus ubicaciones desde una sola cuenta con reglas a nivel de ubicación.",
    "Three locations included": "Tres ubicaciones incluidas",
    "Central dashboard": "Panel central",
    "Location-specific rules": "Reglas específicas por ubicación",
    "Team access": "Acceso para el equipo",
    "Additional locations available": "Ubicaciones adicionales disponibles",
    "Start Multi-Location Trial": "Iniciar Prueba Multi-Ubicación",
    "*Unlimited review responses are subject to reasonable-use limits.": "*Las respuestas ilimitadas a reseñas están sujetas a límites de uso razonable.",
    "14-day free trial. Cancel anytime.": "Prueba gratuita de 14 días. Cancela en cualquier momento.",
    "Frequently Asked Questions": "Preguntas Frecuentes",
    "Which review platforms does ReplyVera support?": "¿Qué plataformas de reseñas admite ReplyVera?",
    "ReplyVera currently supports Google Reviews through Google Business Profile. Facebook, Trustpilot, Booking.com, and Tripadvisor are planned for future releases but are not currently available.": "Actualmente, ReplyVera admite Reseñas de Google a través del Perfil de Empresa de Google. Facebook, Trustpilot, Booking.com y Tripadvisor están planeados para futuras versiones, pero no están disponibles actualmente.",
    "Can I approve responses before they are published?": "¿Puedo aprobar las respuestas antes de que se publiquen?",
    "Yes. On the Starter plan, all replies go through your approval queue before publishing. On Autopilot, you choose which review types can publish automatically and which require your sign-off.": "Sí. En el plan Starter, todas las respuestas pasan por tu cola de aprobación antes de publicarse. En el plan Piloto Automático, eliges qué tipos de reseñas pueden publicarse automáticamente y cuáles requieren tu aprobación.",
    "Can positive reviews be answered automatically?": "¿Se pueden responder automáticamente las reseñas positivas?",
    "Yes. With the Autopilot plan, routine positive reviews can be published automatically based on your configuration. Negative and sensitive reviews are always held for approval.": "Sí. Con el plan Piloto Automático, las reseñas positivas rutinarias se pueden publicar automáticamente según tu configuración. Las reseñas negativas y delicadas siempre se retienen para su aprobación.",
    "Does ReplyVera support multiple locations?": "¿Admite ReplyVera múltiples ubicaciones?",
    "Yes. The Multi-Location plan lets you manage multiple Google Business Profile locations from one dashboard, with separate rules and tone settings for each location.": "Sí. El plan Multi-Ubicación te permite gestionar múltiples ubicaciones del Perfil de Empresa de Google desde un solo panel, con reglas y configuraciones de tono separadas para cada ubicación.",
    "Can I cancel at any time?": "¿Puedo cancelar en cualquier momento?",
    "Yes. There is no long-term contract. You can cancel your subscription at any time from your account settings with no cancellation fees.": "Sí. No hay contratos a largo plazo. Puedes cancelar tu suscripción en cualquier momento desde la configuración de tu cuenta sin cargos de cancelación.",
    "Start Answering Every Google Review": "Comienza a Responder Cada Reseña de Google",
    "Connect your Google Business Profile and let Vera handle routine responses while you stay in control of sensitive feedback.": "Conecta tu Perfil de Empresa de Google y deja que Vera se encargue de las respuestas de rutina mientras mantienes el control sobre los comentarios delicados.",
    "View Pricing": "Ver Precios",
    "ReplyVera G Auto-Reply to Google Reviews with AI": "ReplyVera G Autorespuesta a Reseñas de Google con IA",
    "G 14-Day Free Trial - No Credit Card Required": "G Prueba Gratuita de 14 Días - Sin Tarjeta de Crédito",
    "Automate Google Review Replies with": "Automatiza Respuestas a Reseñas de Google con",
    "Intelligent AI": "IA Inteligente",
    "Instantly craft and post brand-perfect responses to every customer review. Save hours of manual work and build an online reputation that drives revenue.": "Elabora y publica al instante respuestas perfectas y acordes a la marca para cada reseña de cliente. Ahorra horas de trabajo manual y construye una reputación en línea que genere ingresos.",
    "Start 14-Day Free Trial": "Comenzar Prueba Gratuita de 14 Días",
    "Try Live Demo": "Probar Demo en Vivo",
    "G LIVE DEMO": "G DEMO EN VIVO",
    "PASTE A SAMPLE REVIEW": "PEGA UNA RESEÑA DE EJEMPLO",
    "Loved the vibe at the hostel! The staff was friendly, but the bathrooms were a bit crowded in the morning.": "¡Me encantó el ambiente en el hostal! El personal era amable, pero los baños estaban un poco abarrotados por la mañana.",
    "STAR RATING": "CALIFICACIÓN DE ESTRELLAS",
    "GGGGG (5)": "GGGGG (5)",
    "GGGG (4)": "GGGG (4)",
    "GGG (3)": "GGG (3)",
    "GG (2)": "GG (2)",
    "G (1)": "G (1)",
    "BRAND TONE": "TONO DE MARCA",
    "Friendly": "Amistoso",
    "Professional": "Profesional",
    "Premium": "Premium",
    "Generate AI Response": "Generar Respuesta de IA",
    "VERA'S DRAFT RESPONSE": "BORRADOR DE RESPUESTA DE VERA",
    "Ready to Post": "Listo para Publicar",
    "Unanswered Reviews Cost You Customers.": "Las Reseñas Sin Responder te Cuestan Clientes.",
    "In today's market, your reputation is your revenue. Ignoring customer feedback is no longer an option.": "En el mercado actual, tu reputación es tu ingreso. Ignorar los comentarios de los clientes ya no es una opción.",
    "It Takes Too Much Time": "Toma Demasiado Tiempo",
    "Writing thoughtful, personalized responses for every single review takes hours out of your busy week.": "Escribir respuestas reflexivas y personalizadas para cada reseña toma horas de tu ocupada semana.",
    "Businesses Stay Silent": "Las Empresas Se Quedan Calladas",
    "Over 75% of businesses fail to reply to their reviews, sending a message that they don't value their customers.": "Más del 75% de las empresas no responden a sus reseñas, enviando un mensaje de que no valoran a sus clientes.",
    "Missed Opportunities": "Oportunidades Perdidas",
    "Google prioritizes active businesses. Unanswered reviews hurt your local SEO rank and conversion rates.": "Google prioriza a las empresas activas. Las reseñas sin responder perjudican tu ranking de SEO local y las tasas de conversión.",
    "Intelligent Workflow": "Flujo de Trabajo Inteligente",
    "Your Autopilot for Customer Relationships": "Tu Piloto Automático para Relaciones con los Clientes",
    "ReplyVera transforms how you handle customer feedback. It's like having a dedicated PR manager working 24/7.": "ReplyVera transforma la forma en que manejas los comentarios de los clientes. Es como tener un gerente de relaciones públicas dedicado trabajando 24/7.",
    "Smart AI Replies": "Respuestas Inteligentes con IA",
    "Generates context-aware, empathetic responses based on the specific content of the review.": "Genera respuestas empáticas y conscientes del contexto basadas en el contenido específico de la reseña.",
    "Safe & Controlled": "Seguro y Controlado",
    "Set up guardrails. Require manual approval before posting, or enable full automation for 5-star reviews.": "Establece límites. Requiere aprobación manual antes de publicar o habilita la automatización completa para reseñas de 5 estrellas.",
    "Matches Your Brand Tone": "Coincide con el Tono de tu Marca",
    "Customize the AI to sound just like you. Whether it's professional, friendly, or playful.": "Personaliza la IA para que suene exactamente como tú. Ya sea profesional, amistoso o divertido.",
    "AI Tone Settings": "Ajustes de Tono de IA",
    "Appreciative": "Agradecido",
    "Analyzing sentiment...": "Analizando sentimiento...",
    "Positive (0.94)": "Positivo (0.94)",
    "Extracting keywords...": "Extrayendo palabras clave...",
    "\"Helpful team\"": "\"Equipo servicial\"",
    "Drafting response...": "Redactando respuesta...",
    "Generating...": "Generando...",
    "Simple Setup": "Configuración Sencilla",
    "Three Steps to Reputation Mastery": "Tres Pasos para el Dominio de la Reputación",
    "A seamless setup process that has you running in under five minutes.": "Un proceso de configuración perfecto que te tiene funcionando en menos de cinco minutos.",
    "Connect Google": "Conectar Google",
    "Link your Google Business Profile via secure OAuth. No passwords required.": "Vincule su perfil de empresa de Google a través de un sistema OAuth seguro. No se requieren contraseñas.",
    "AI Generates Replies": "IA Genera Respuestas",
    "ReplyVera instantly drafts the perfect response whenever a new review drops.": "ReplyVera redacta instantáneamente la respuesta perfecta cada vez que llega una nueva reseña.",
    "Approve or Auto-Post": "Aprobar o Auto-Publicar",
    "Review the draft and click approve, or turn on full autopilot and let it run.": "Revisa el borrador y haz clic en aprobar, o activa el piloto automático completo y déjalo funcionar.",
    "Enterprise-Grade Privacy": "Privacidad de Grado Empresarial",
    "Engineered for safety.": "Diseñado para la seguridad.",
    "We take your business reputation seriously. Our architecture is designed to prioritize the security of your data and the integrity of your brand.": "Nos tomamos en serio la reputación de tu empresa. Nuestra arquitectura está diseñada para priorizar la seguridad de tus datos y la integridad de tu marca.",
    "We use secure Google OAuth. We never see your password.": "Usamos Google OAuth seguro. Nunca vemos tu contraseña.",
    "No Passwords Stored.": "Sin Contraseñas Almacenadas.",
    "Nothing is posted without your permission unless you explicitly enable auto-post rules.": "No se publica nada sin tu permiso a menos que habilites explícitamente las reglas de auto-publicación.",
    "You're in Control.": "Tú Tienes el Control.",
    "All data is encrypted in transit and at rest.": "Todos los datos están cifrados en tránsito y en reposo.",
    "Bank-Level Security.": "Seguridad a Nivel Bancario.",
    "100% Secure": "100% Seguro",
    "Pricing Plans": "Planes de Precios",
    "Fair, Transparent Pricing": "Precios Justos y Transparentes",
    "Choose the tier that fits your business needs. Cancel or change plans anytime.": "Elige el nivel que se adapte a las necesidades de tu empresa. Cancela o cambia de plan en cualquier momento.",
    "/month": "/mes",
    "Perfect for small local shops managing their initial online growth.": "Perfecto para pequeñas tiendas locales que manejan su crecimiento inicial en línea.",
    "1 Location": "1 Ubicación",
    "Up to 50 review replies/mo": "Hasta 50 respuestas a reseñas/mes",
    "Manual approval workflow": "Flujo de trabajo de aprobación manual",
    "Email support": "Soporte por correo electrónico",
    "Growth Autopilot": "Piloto Automático de Crecimiento",
    "$79": "$79",
    "Autopilot reply rules for franchises and growing businesses.": "Reglas de respuesta en piloto automático para franquicias y negocios en crecimiento.",
    "Multi-Location Support": "Soporte Multi-Ubicación",
    "Unlimited reviews & auto-replies": "Reseñas y autorespuestas ilimitadas",
    "Live Autopilot (Auto-Post) rules": "Reglas de Piloto Automático en vivo (Auto-Publicación)",
    "Custom Brand Tone settings": "Ajustes personalizados de Tono de Marca",
    "Priority support": "Soporte prioritario",
    "Agency & Enterprise": "Agencia y Empresa",
    "$199": "$199",
    "For agencies managing hundreds of customer storefront profiles.": "Para agencias que gestionan cientos de perfiles de tiendas de clientes.",
    "Unlimited locations": "Ubicaciones ilimitadas",
    "Custom API & webhook integrations": "Integraciones personalizadas de API y webhooks",
    "Dedicated Account Manager": "Gerente de Cuenta Dedicado",
    "SLA guarantees": "Garantías de SLA",
    "Contact Sales": "Contactar a Ventas",
    "Don't let another review go unanswered.": "No dejes que otra reseña quede sin responder.",
    "Ensure every customer receives a perfect response. Start saving time and boosting your local SEO today.": "Asegúrate de que cada cliente reciba una respuesta perfecta. Comienza a ahorrar tiempo y mejora tu SEO local hoy.",
    "Get Started Instantly": "Comienza al Instante",
    "Have questions? Contact us at": "¿Tienes preguntas? Contáctanos en",
    "The review autopilot trusted by 2,400+ storefronts, franchises, and agencies. Save 30+ hours a month while ensuring every customer receives a perfect, professional response.": "El piloto automático de reseñas en el que confían más de 2,400 tiendas, franquicias y agencias. Ahorra más de 30 horas al mes mientras te aseguras de que cada cliente reciba una respuesta profesional perfecta.",
    "ReplyVera Pricing – Simple, Transparent Pricing": "Precios de ReplyVera – Precios Sencillos y Transparentes",
    "Agency": "Agencia",
    "Simple Pricing. No Sales Call Required.": "Precios Sencillos. Sin Llamadas de Ventas.",
    "Choose the level of automation and number of locations that fit your business.": "Elige el nivel de automatización y la cantidad de ubicaciones que se adapten a tu negocio.",
    "Monthly": "Mensual",
    "Annual": "Anual",
    "Save 2 Months": "Ahorra 2 Meses",
    "For businesses that approve every reply before publishing.": "Para empresas que aprueban cada respuesta antes de publicar.",
    "/ month": "/ mes",
    "1 business location": "1 ubicación de negocio",
    "For businesses that want safe review replies published automatically.": "Para empresas que desean publicar automáticamente respuestas seguras.",
    "For businesses managing several locations.": "Para empresas que gestionan varias ubicaciones.",
    "From": "Desde",
    "For agencies managing Google review replies for multiple clients.": "Para agencias que gestionan respuestas de reseñas de Google de múltiples clientes.",
    "$149": "$149",
    "10 client locations included": "10 ubicaciones de clientes incluidas",
    "Multi-client dashboard": "Panel multi-cliente",
    "Separate client brand voices": "Voces de marca separadas por cliente",
    "Client approval access": "Acceso de aprobación de clientes",
    "Agency reporting": "Informes de agencia",
    "Start Agency Trial": "Iniciar Prueba de Agencia",
    "Compare All Features": "Comparar Todas las Características",
    "Locations included": "Ubicaciones incluidas",
    "3 Locations": "3 Ubicaciones",
    "10 Locations": "10 Ubicaciones",
    "Monthly reply limit": "Límite mensual de respuestas",
    "30 replies": "30 respuestas",
    "Unlimited": "Ilimitadas",
    "Included": "Incluido",
    "Automatic publishing": "Publicación automática",
    "Not included": "No incluido",
    "Employee-name recognition": "Reconocimiento de nombre de empleado",
    "Multi-location reporting": "Informes de múltiples ubicaciones",
    "Client dashboard": "Panel de cliente",
    "Support level": "Nivel de soporte",
    "Standard": "Estándar",
    "Priority": "Prioritario",
    "Dedicated": "Dedicado",
    "Yes. ReplyVera is billed monthly or annually, and you can cancel before your next billing date.": "Sí. ReplyVera se factura mensual o anualmente, y puedes cancelar antes de tu próxima fecha de facturación.",
    "Is there a setup fee?": "¿Hay alguna tarifa de instalación?",
    "No. There is no setup fee for standard plans.": "No. No hay tarifas de instalación en los planes estándar.",
    "Does each location need its own plan?": "¿Necesita cada ubicación su propio plan?",
    "Starter and Autopilot include one location. Multi-location and Agency plans include several locations and allow additional locations to be added for a fee.": "Starter y Piloto Automático incluyen una ubicación. Los planes Multi-Ubicación y Agencia incluyen varias ubicaciones y permiten agregar ubicaciones adicionales por una tarifa.",
    "Are replies unlimited?": "¿Son ilimitadas las respuestas?",
    "The Starter plan includes up to 30 replies per month. Autopilot, Multi-Location, and Agency plans include unlimited responses subject to reasonable-use limits.": "El plan Starter incluye hasta 30 respuestas por mes. Los planes Piloto Automático, Multi-Ubicación y Agencia incluyen respuestas ilimitadas sujetas a límites de uso razonable.",
    "Which review platforms are supported?": "¿Qué plataformas de reseñas se admiten?",
    "ReplyVera currently supports Google Reviews. Facebook, Trustpilot, Booking.com, and Tripadvisor are planned for future releases.": "Actualmente, ReplyVera admite Reseñas de Google. Facebook, Trustpilot, Booking.com y Tripadvisor están planeados para futuras versiones.",
    "Can I change plans later?": "¿Puedo cambiar de plan más adelante?",
    "Yes. You can upgrade or downgrade your plan as your review volume or number of locations changes.": "Sí. Puedes actualizar o degradar tu plan a medida que cambia el volumen de tus reseñas o la cantidad de ubicaciones.",
    "Currently supported: Google Reviews": "Actualmente compatible: Reseñas de Google",
    "Facebook, Trustpilot, Booking.com, and Tripadvisor are planned for future releases.": "Facebook, Trustpilot, Booking.com y Tripadvisor están planeados para futuras versiones.",
    "Ready to automate your Google review replies?": "¿Listo para automatizar tus respuestas a las reseñas de Google?",
    "The review autopilot built for storefronts, franchises, and agencies to protect their online reputation.": "El piloto automático de reseñas creado para tiendas, franquicias y agencias para proteger su reputación en línea.",
    "Login": "Iniciar Sesión",
    "Privacy Policy | ReplyVera": "Política de Privacidad | ReplyVera",
    "At ReplyVera, we value your privacy and the trust you place in us to manage your online reputation. This Privacy Policy explains how we collect, use, and protect your information when you use our service.": "Bij ReplyVera hechten we waarde aan uw privacy en het vertrouwen dat u in ons stelt om uw online reputatie te beheren. Dit Privacybeleid legt uit hoe we uw informatie verzamelen, gebruiken en beschermen wanneer u onze service gebruikt.",
    "1. Information We Collect": "1. Informatie die we verzamelen",
    "We collect information to provide a better service to all our users. This includes:": "We verzamelen informatie om een betere service te bieden aan al onze gebruikers. Dit omvat:",
    "When you sign up, we collect your email address and basic profile information via Google OAuth.": "Wanneer u zich aanmeldt, verzamelen we uw e-mailadres en basale profielinformatie via Google OAuth.",
    "Account Information:": "Accountinformatie:",
    "To operate our core service, we request access to your Google Business Profile. This includes review content, reviewer names, and location data.": "Om onze kernservice uit te voeren, vragen we toegang tot uw Google Bedrijfsprofiel. Dit omvat de inhoud van reviews, namen van reviewers en locatiegegevens.",
    "Google Business Profile Data:": "Google Bedrijfsprofielgegevens:",
    "We may collect information about how you interact with our dashboard to improve our user interface and AI performance.": "We kunnen informatie verzamelen over hoe u met ons dashboard communiceert om onze gebruikersinterface en AI-prestaties te verbeteren.",
    "Usage Data:": "Gebruiksgegevens:",
    "2. How We Use Information": "2. Hoe we informatie gebruiken",
    "We use the data we collect for the following purposes:": "We gebruiken de gegevens die we verzamelen voor de volgende doeleinden:",
    "To draft and post replies to your Google reviews using AI.": "Om reacties op uw Google-reviews op te stellen en te plaatsen met behulp van AI.",
    "To provide analytics on your review performance.": "Om analyses van uw reviewprestaties te bieden.",
    "To communicate with you about your account and service updates.": "Om met u te communiceren over uw account en service-updates.",
    "To improve our AI algorithms for more accurate and helpful responses.": "Om onze AI-algoritmen te verbeteren voor nauwkeuriger en nuttiger reacties.",
    "3. Limited Use for Google User Data": "3. Beperkt gebruik van Google-gebruikersgegevens",
    "ReplyVera's use and transfer to any other app of information received from Google APIs will adhere to the": "Het gebruik en de overdracht van ReplyVera naar enige andere app van informatie die is ontvangen van Google API's zal voldoen aan het",
    ", including the Limited Use requirements.": ", inclusief de vereisten voor Beperkt Gebruik.",
    "Google API Services User Data Policy": "Beleid voor Gebruikersgegevens van Google API-services",
    "We do not use your Google data for serving advertisements, and we do not sell your data to third parties.": "We gebruiken uw Google-gegevens niet voor het weergeven van advertenties en we verkopen uw gegevens niet aan derden.",
    "4. Data Retention": "4. Dataretentie",
    "We retain your information as long as your account is active. If you disconnect your Google Account or delete your ReplyVera account, we will remove your tokens and cease data collection immediately.": "We bewaren uw informatie zolang uw account actief is. Als u uw Google-account loskoppelt of uw ReplyVera-account verwijdert, verwijderen we uw tokens en stoppen we onmiddellijk met het verzamelen van gegevens.",
    "5. Security": "5. Veiligheid",
    "We implement industry-standard security measures, including encryption at rest and in transit, to protect your data from unauthorized access or disclosure.": "We implementeren industriestandaard beveiligingsmaatregelen, inclusief encryptie in rust en tijdens verzending, om uw gegevens te beschermen tegen ongeautoriseerde toegang of openbaarmaking.",
    "If you have any questions about this Privacy Policy, please contact us at": "Als u vragen heeft over dit Privacybeleid, neem dan contact met ons op via",
    "Terms of Service | ReplyVera": "Servicevoorwaarden | ReplyVera",
    "By using the ReplyVera service (\"Service\"), you agree to the following terms and conditions. If you do not agree, please do not use the Service.": "Door de ReplyVera-service (\"Service\") te gebruiken, gaat u akkoord met de volgende voorwaarden. Als u niet akkoord gaat, gebruik de Service dan niet.",
    "1. The Service": "1. De Service",
    "ReplyVera provides an AI-assisted review management platform designed to help businesses draft and manage replies to Google Business Profile reviews. The Service includes automated drafting and, where enabled, automated posting of replies.": "ReplyVera biedt een AI-ondersteund platform voor reviewbeheer, ontworpen om bedrijven te helpen bij het opstellen en beheren van reacties op Google Bedrijfsprofiel-reviews. De Service omvat het automatisch opstellen en, indien ingeschakeld, automatisch plaatsen van reacties.",
    "2. User Responsibilities": "2. Verantwoordelijkheden van de Gebruiker",
    "You are responsible for the content posted to your Google Business Profile. While ReplyVera uses advanced AI to draft responses, you acknowledge that:": "U bent verantwoordelijk voor de inhoud die op uw Google Bedrijfsprofiel wordt geplaatst. Hoewel ReplyVera geavanceerde AI gebruikt om reacties op te stellen, erkent u dat:",
    "Automated replies are generated based on AI models and may not always be perfect.": "Automatische reacties worden gegenereerd op basis van AI-modellen en zijn mogelijk niet altijd perfect.",
    "You have the option to review all drafts before they go live.": "U heeft de mogelijkheid om alle concepten te bekijken voordat ze live gaan.",
    "You must comply with Google's Business Profile policies at all times.": "U moet te allen tijde voldoen aan het beleid van Google Bedrijfsprofiel.",
    "3. Access and Permissions": "3. Toegang en Rechten",
    "By connecting your Google Account, you grant ReplyVera permission to access your Google Business Profile, read reviews, and post replies on your behalf. You can revoke this access at any time via your Google Account settings or our Dashboard.": "Door uw Google-account te koppelen, verleent u ReplyVera toestemming om toegang te krijgen tot uw Google Bedrijfsprofiel, reviews te lezen en namens u reacties te plaatsen. U kunt deze toegang op elk moment intrekken via de instellingen van uw Google-account of ons Dashboard.",
    "4. Subscription and Payments": "4. Abonnement en Betalingen",
    "ReplyVera is a subscription-based service. You agree to pay all fees associated with your chosen plan. All payments are processed via our secure third-party provider (Stripe). You may cancel your subscription at any time.": "ReplyVera is een abonnementsservice. U stemt ermee in om alle kosten te betalen die verband houden met uw gekozen abonnement. Alle betalingen worden verwerkt via onze beveiligde externe provider (Stripe). U kunt uw abonnement op elk moment annuleren.",
    "5. Limitation of Liability": "5. Beperking van Aansprakelijkheid",
    "ReplyVera is provided \"as is.\" We are not liable for any damages, loss of reputation, or Google account suspensions resulting from the use of the Service or the content of the AI-generated replies.": "ReplyVera wordt geleverd \"zoals het is\". Wij zijn niet aansprakelijk voor enige schade, reputatieverlies of schorsingen van Google-accounts als gevolg van het gebruik van de Service of de inhoud van de door AI gegenereerde reacties.",
    "6. Termination": "6. Beëindiging",
    "We reserve the right to suspend or terminate accounts that violate these terms, use the service for spam, or engage in deceptive practices regarding customer reviews.": "We behouden ons het recht voor om accounts op te schorten of te beëindigen die deze voorwaarden schenden, de service gebruiken voor spam of zich inlaten met misleidende praktijken met betrekking tot klantbeoordelingen.",
    "7. Changes to Terms": "7. Wijzigingen in Voorwaarden",
    "We may update these Terms from time to time. Your continued use of the Service after changes are posted constitutes acceptance of the new Terms.": "We kunnen deze Voorwaarden van tijd tot tijd bijwerken. Uw voortgezette gebruik van de Service na publicatie van wijzigingen vormt de acceptatie van de nieuwe Voorwaarden.",
    "8. Contact Us": "8. Neem contact met ons op",
    "If you have any questions about these Terms, please contact us at": "Als u vragen heeft over deze Voorwaarden, neem dan contact met ons op via",
}

with open(source_file, 'r', encoding='utf-8') as f:
    data = json.load(f)

for k, v in data.items():
    if v in translations:
        data[k] = translations[v]
    # Otherwise leave the original value intact (e.g. CSS, Javascript snippets)

with open(dest_file, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Successfully generated {dest_file}")
