/**
 * ReplyVera — Legal Configuration & Company Information
 * 
 * Central registry for official entity and billing details.
 * 
 * TODO for Owner:
 * Enter your registered entity name, registered office address, Chamber of Commerce (KvK)
 * number, and VAT identification number once incorporation/registration is complete.
 * NOTE: Never display unverified or bracketed placeholders to visitors.
 */
const LEGAL_CONFIG = {
    // Official Business Entity (Pending Owner Input - Leave null until officially registered)
    entityName: null,        // e.g. "ReplyVera B.V." or legal entity name
    registeredAddress: null, // e.g. "Official registered address"
    registrationNumber: null,// Chamber of Commerce / Commercial Register (e.g. KvK)
    vatNumber: null,         // VAT / Tax Identification Number

    // Support & Communication
    supportEmail: "info@replyvera.com",
    serviceName: "ReplyVera",
    websiteUrl: "https://www.replyvera.com",

    // Merchant of Record (Paddle) - Verified Live Partner
    merchantOfRecord: {
        name: "Paddle.com Market Ltd",
        address: "Judd House, 18-29 Mora Street, London EC1V 8BT, UK",
        role: "Merchant of Record for all orders, checkout, invoicing, currency conversion, and applicable sales tax remittance."
    },

    // Fair Use Policy Definition
    fairUsePolicy: {
        summary: "Unlimited review responses under our Fair Use Policy are designed for normal review activity at your enrolled business locations.",
        termsClause: "Unlimited review responses are intended for genuine, ordinary review traffic generated by customers of enrolled business locations. Automated bulk abuse, reselling outside designated plans, artificial review generation, or traffic that materially impairs infrastructure stability is prohibited and may result in rate-limiting or plan reclassification."
    }
};

module.exports = LEGAL_CONFIG;
